import {
  PDFViewer,
  Document,
  Page,
  View,
  Text,
} from "@react-pdf/renderer";
import { styles } from "./style";

const InvoicePDF = () => (
  <Document title="Statement_Sam_2026">
    <Page size="A4" style={styles.page}>
      {/* Header section matching Statement_Crok_2026.pdf */}
      <View style={styles.header}>
        <Text style={styles.title} color="#4f46e5">Clubs</Text>
        <Text style={styles.subtitle}>MEMBER ACCOUNT STATEMENT</Text>
      </View>

      {/* Metadata */}
      <View style={styles.metaData}>
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Report Period:</Text>
          <Text style={styles.metaCell}>FY 2026</Text>
        </View>
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Generated on:</Text>
          <Text style={styles.metaCell}>10/09/2026, 12:24:01</Text>
        </View>
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Beneficiary:</Text>
          <Text style={styles.metaCell}>Sam</Text>
        </View>
        <View style={styles.metaRow}>
          <Text style={styles.metaLabel}>Current Account Status:</Text>
          <Text style={styles.metaCell}>Arrears</Text>
        </View>
      </View>

      {/* Table */}
      <View style={styles.table}>
        <View style={styles.tableHeaderRow}>
          <View style={styles.tableCol}><Text style={styles.tableCellHeader}>Date</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCellHeader}>Cycle</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCellHeader}>Description</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCellHeader}>Method</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCellHeader}>Amount</Text></View>
        </View>
        
        {/* Sample rows totalling the R 1500,00 paid shown in your dashboard */}
        <View style={styles.tableRow}>
          <View style={styles.tableCol}><Text style={styles.tableCell}>2026-07-08</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>July</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>Monthly Contribution</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>Cash</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>R 500,00</Text></View>
        </View>
        <View style={styles.tableRow}>
          <View style={styles.tableCol}><Text style={styles.tableCell}>2026-08-08</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>August</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>Monthly Contribution</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>Cash</Text></View>
          <View style={styles.tableCol}><Text style={styles.tableCell}>R 1 000,00</Text></View>
        </View>
      </View>

      {/* Annual Summary */}
      <View style={styles.summary}>
        <Text style={styles.summaryHeader}>Annual Summary</Text>
        <View style={styles.summaryRow}>
          <Text style={styles.summaryLabel}>Total Payments Expected (to date):</Text>
          {/* Example expected based on R 500/mo */}
          <Text style={styles.summaryValue}>R 2 000,00</Text> 
        </View>
        <View style={styles.summaryRow}>
          <Text style={styles.summaryLabel}>Total Payments Recorded:</Text>
          <Text style={styles.summaryValue}>R 1 500,00</Text>
        </View>
        <View style={styles.summaryRow}>
          <Text style={styles.summaryLabel}>Arrears Balance:</Text>
          <Text style={styles.summaryValue}>R 500,00</Text>
        </View>
      </View>

      {/* Footer */}
      <View style={styles.footer} fixed>
        <Text>Generated by Scheme Manager Pro - Official Member Statement</Text>
        <Text render={({ pageNumber, totalPages }) => (`Page ${pageNumber} of ${totalPages}`)} />
      </View>
    </Page>
  </Document>
);

export default function MemberAccountStatement() {
  return (
    <div className="w-full h-full">
      <PDFViewer width="100%" height="100%">
        <InvoicePDF />
      </PDFViewer>
    </div>
  );
}